# @package _global_

defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml

task_name: "demo_traced"

# checkpoint is necessary for demo
ckpt_path: /workspace/emlo_v2_cifar10_hydra/logs/train/runs/2022-11-18_12-20-35/model_script.pt
